### ISSUE TITLE
Update Text content on Page 

### ISSUE THREAD

**Issue by dar1ooo** [dar1ooo/CyberGen-landing-page#14]
Here is a link to the content which should be used in the different sections among the landing page
[here](https://docs.google.com/document/d/1UQuB9aMsK86zjHJjgk5lxS3sLpWgFl5q7FdModHpMIw/edit#heading=h.jlup1n2ryleu)

**Comment by TheDeGen** [comment]
NOW

**Comment by dar1ooo** [comment]
text content has been updated
