### ISSUE TITLE
Button stacking issue

### ISSUE THREAD

**Issue by TheDeGen** [dar1ooo/CyberGen-landing-page#19]
On the mobile version, the adaptability keeps them sticked close together. I saw that after a certain width (around 455px) both buttons become very small, when that height is reached, is it possible to rather stack the buttons on top of one another?

See pic: 
![image](https://user-images.githubusercontent.com/93676606/143904216-e5735a7a-0cc0-4138-8702-68faa8ebcd18.png)

So Mint button first, then Discord, colours are the same

**Comment by dar1ooo** [comment]
![image](https://user-images.githubusercontent.com/63245314/143943656-bc4d6319-94d6-429a-b96c-04443dc1ef2e.png)
like this ?

**Comment by dar1ooo** [comment]
changed button stacking on mobile
