### ISSUE TITLE
Stacking Issue Buttons & Title

### ISSUE THREAD

**Issue by TheDeGen** [dar1ooo/CyberGen-landing-page#20]
**THIS IS LOW PRIORITY**

In a certain awkward aspect ratio, the title and buttons overlap. This doesn't happen in mobile view, just PC view

![image](https://user-images.githubusercontent.com/93676606/143904533-fb30641f-3fbe-4cd4-82c6-c9fec9be4b93.png)

**Comment by dar1ooo** [comment]
this issue is a duplicate

**Comment by dar1ooo** [comment]
stacking issue has been fixed
shadow has been removed and error message has been changed to toastr
