### ISSUE TITLE
Gallery Adjustments

### ISSUE THREAD

**Issue by TheDeGen** [dar1ooo/CyberGen-landing-page#21]
(See pic below for reference)

1 & 3) Can we reduce the space here by 50%, thing seem to be a little too far apart. This isn't extremely important but makes everything look cleaner

2) On mobile reduce the amount of images from 6 to 4 images. Remove the **view more** button. On PC, keep it at 6 and remove the view more button too

![image](https://user-images.githubusercontent.com/93676606/143905267-26be0e93-f901-45f7-93e2-a4c200b688e4.png)

**Comment by dar1ooo** [comment]
gallery image count adjusted removed buttons to show more images
