### ISSUE TITLE
Shadow stacking issue

### ISSUE THREAD

**Issue by TheDeGen** [dar1ooo/CyberGen-landing-page#23]
In a 4:3 aspect ratio on PC, the shadow gradient sometimes jumps in front of the buttons, see pic

![image](https://user-images.githubusercontent.com/93676606/143906038-c536fbbe-ce68-42ab-919d-bc5fee5e5e9d.png)

**Comment by dar1ooo** [comment]
stacking issue has been fixed
shadow has been removed and error message has been changed to toastr
