### ISSUE TITLE
Shadow Stacking Issue + background rescale Issue

### ISSUE THREAD

**Issue by TheDeGen** [dar1ooo/CyberGen-landing-page#30]
On the mobile version, once the page loads, the shadow is in front of the buttons (should be behind)
![image](https://user-images.githubusercontent.com/93676606/144636558-c67d757d-1a48-46d4-8455-ab5457386aa6.png)

Also when starting to scroll down the shadow disappears and the background image rescales for some reason, making everything feel laggy

**Comment by dar1ooo** [comment]
stacking issue has been fixed
shadow has been removed and error message has been changed to toastr
