### ISSUE TITLE
Horizontal Spacing Issue

### ISSUE THREAD

**Issue by TheDeGen** [dar1ooo/CyberGen-landing-page#32]
On _Desktop_, in the _What is CyberGen_section, the space between the image and text is too large, reduce it by 50%

Also make sure the text is centered vertically to the pic

![image](https://user-images.githubusercontent.com/93676606/144637529-d274ff53-f194-422d-8c82-1e6d2f974461.png)

**Comment by dar1ooo** [comment]
spacing has been fixed
