### ISSUE TITLE
Team Pictures

### ISSUE THREAD

**Issue by TheDeGen** [dar1ooo/CyberGen-landing-page#6]
Please change the team section as follows

**Colours**
Background should be: #01618B (it probably already is)
Brackground on hover should be: Gradient from #FC32AA to #23DCEB
![image](https://user-images.githubusercontent.com/93676606/141797093-c13853e2-9153-411f-a782-739282e5e6d8.png

**Pictures**
The background image is rounded, whilst the profile pic has sharp edges, is it possible to me them both rounded and uniform? I can see it's done using angular so I'm unaware how precise you can be. I tried looking into `cyber.aboutus.component.ts` but couldn't find anything.
![image](https://user-images.githubusercontent.com/93676606/141798497-d2e2776c-7c8e-42b9-97e5-72262ae0c4e0.png)

**Comment by TheDeGen** [comment]
Version 2

**Comment by dar1ooo** [comment]
Colors and Pictures have been adjusted
