### ISSUE TITLE
Title Stacking Issue

### ISSUE THREAD

**Issue by TheDeGen** [dar1ooo/CyberGen-landing-page#7]
**LOW PRIORITY**

When the window has reduced the title How is it generated stacks on top of each other? See pic

![image](https://user-images.githubusercontent.com/93676606/141799409-b0f7eb75-9ffd-4e70-a091-a1500b654146.png)

Not sure if it's possible to code in an automatic paragraph when it gets too narrow in `cyber.ai.component.scss`, otherwise I'm guessing it's all declared separately and imported in `cyber.ai.component.ts`

**Comment by dar1ooo** [comment]
Yup gonna work on this today
First part was getting the base layout now i gotta make it responsive for different view port sizes (including mobile view which looks terrible atm)

**Comment by dar1ooo** [comment]
Has been resolved
