### ISSUE TITLE
Landing Page Background

### ISSUE THREAD

**Issue by TheDeGen** [dar1ooo/CyberGen-landing-page#8]
@TheDeGen needs to create a High-Res (at least 1080x1920) Background picture to have as the backdrop.

Optional: create high res, very dark images to use throughout the website.

**Comment by TheDeGen** [comment]
@dar1ooo can you confirm that video backgrounds (or using a high-res GIF) is hard to implement?

**Comment by dar1ooo** [comment]
@TheDeGen well i tried the video. Implementing was easy there were just a few bugs i wasn't sure how to fix

With the high res pics
- we need to watch out that the loading amount isn't too high or else the page loads with no images and they just appear out of nowhere when it's done dowloading (for users with slow internet)
- it will increase our bandwidth

**Comment by TheDeGen** [comment]
@dar1ooo yeah that makes a lot of sense. Maybe the vid is too much bandwidth. I'll make sure the high-res pic is properly compressed. It should be like the pic we have now, but just our own

**Comment by TheDeGen** [comment]
I like how it is now
