### ISSUE TITLE
C2A Button under welcome screen

### ISSUE THREAD

**Issue by TheDeGen** [dar1ooo/CyberGen-landing-page#9]
The Mint & Discord buttons are too low on the page. The current layout is increasing our bounce rate (people who click a website and leave without doing anything). 

Ideally below the welcome to CyberGen City 

see this website for reference: https://abduct.me/

**Comment by TheDeGen** [comment]
@dar1ooo this one is the only UI feature you should work one before we finalize the visual identity

**Comment by dar1ooo** [comment]
Has been implemented. Might need to change styling later on
